/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.Vista.secciones;
import BD.CMenu;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Sofia Useche
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public File archivoseleccionado;
    private ImageIcon imageIcon;
    private CMenu objetoMenu;
    public Menu() {
        initComponents();
        PanelCubierta.setVisible(false);
        objetoMenu = new CMenu(this);
        txtCodigo.setEnabled(false);
        txtUrlImagen.setEnabled(false);
        txtUrlImagen1.setEnabled(false);
        objetoMenu.mostrarCategorias(CbCategoria);
        objetoMenu.mostrarCategorias(CbCategoria1);
        mostrarMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        PanelCubierta = new javax.swing.JTabbedPane();
        FormularioNuevo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnExplorar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jlImagen = new javax.swing.JLabel();
        txtUrlImagen = new javax.swing.JTextField();
        txtNombre = new RSMaterialComponent.RSTextFieldMaterial();
        txtPrecio = new RSMaterialComponent.RSTextFieldMaterial();
        CbCategoria = new RSMaterialComponent.RSComboBoxMaterial();
        FormullarioModificar = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BtnGuardarModificar = new javax.swing.JButton();
        BtnSalir1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnExplorar1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jlImagen1 = new javax.swing.JLabel();
        txtUrlImagen1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNombre1 = new RSMaterialComponent.RSTextFieldMaterial();
        txtPrecio1 = new RSMaterialComponent.RSTextFieldMaterial();
        txtCodigo = new RSMaterialComponent.RSTextFieldMaterial();
        CbCategoria1 = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel1 = new javax.swing.JLabel();
        BotonNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        Seccion = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelCarnes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        PanelDelChef = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        PanelEjecutivo = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        PanelSopas = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        PanelPescado = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        PanelBebida = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        PanelAdicional = new javax.swing.JPanel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(789, 660));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelCubierta.setBackground(new java.awt.Color(255, 255, 255));
        PanelCubierta.setPreferredSize(new java.awt.Dimension(800, 700));

        FormularioNuevo.setPreferredSize(new java.awt.Dimension(800, 700));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nuevo Menú");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Categoria");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Precio");

        BtnGuardar.setBackground(new java.awt.Color(58, 179, 28));
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setText("Guardar");
        BtnGuardar.setBorder(null);
        BtnGuardar.setBorderPainted(false);
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnSalir.setBackground(new java.awt.Color(255, 51, 51));
        BtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalir.setText("Cancelar");
        BtnSalir.setBorder(null);
        BtnSalir.setBorderPainted(false);
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imagen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N

        btnExplorar.setBackground(new java.awt.Color(58, 179, 28));
        btnExplorar.setForeground(new java.awt.Color(255, 255, 255));
        btnExplorar.setText("Importar");
        btnExplorar.setBorder(null);
        btnExplorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExplorarActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Imagen seleccionada");

        txtUrlImagen.setBorder(null);
        txtUrlImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUrlImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExplorar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtUrlImagen)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(48, 48, 48))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExplorar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUrlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtNombre.setBorder(null);
        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.setCaretColor(new java.awt.Color(51, 51, 255));
        txtNombre.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtNombre.setDisabledTextColor(new java.awt.Color(51, 204, 0));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNombre.setPhColor(new java.awt.Color(51, 51, 51));
        txtNombre.setPlaceholder("Ingrese el nombre");
        txtNombre.setSelectionColor(new java.awt.Color(51, 51, 51));

        txtPrecio.setForeground(new java.awt.Color(51, 51, 51));
        txtPrecio.setCaretColor(new java.awt.Color(51, 51, 255));
        txtPrecio.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtPrecio.setDisabledTextColor(new java.awt.Color(51, 204, 0));
        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtPrecio.setPhColor(new java.awt.Color(51, 51, 51));
        txtPrecio.setPlaceholder("Ingrese el precio");
        txtPrecio.setSelectionColor(new java.awt.Color(51, 51, 51));

        CbCategoria.setBorder(null);
        CbCategoria.setForeground(new java.awt.Color(51, 51, 51));
        CbCategoria.setColorMaterial(new java.awt.Color(58, 179, 28));
        CbCategoria.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(CbCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FormularioNuevoLayout = new javax.swing.GroupLayout(FormularioNuevo);
        FormularioNuevo.setLayout(FormularioNuevoLayout);
        FormularioNuevoLayout.setHorizontalGroup(
            FormularioNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormularioNuevoLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        FormularioNuevoLayout.setVerticalGroup(
            FormularioNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormularioNuevoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );

        PanelCubierta.addTab("tab1", FormularioNuevo);

        FormullarioModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Modificar Menú");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Nombre");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Categoria");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Precio");

        BtnGuardarModificar.setBackground(new java.awt.Color(58, 179, 28));
        BtnGuardarModificar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardarModificar.setText("Guardar");
        BtnGuardarModificar.setBorder(null);
        BtnGuardarModificar.setBorderPainted(false);
        BtnGuardarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarModificarActionPerformed(evt);
            }
        });

        BtnSalir1.setBackground(new java.awt.Color(255, 51, 51));
        BtnSalir1.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalir1.setText("Cancelar");
        BtnSalir1.setBorder(null);
        BtnSalir1.setBorderPainted(false);
        BtnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalir1ActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imagen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N

        btnExplorar1.setBackground(new java.awt.Color(58, 179, 28));
        btnExplorar1.setForeground(new java.awt.Color(255, 255, 255));
        btnExplorar1.setText("Importar");
        btnExplorar1.setBorder(null);
        btnExplorar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExplorar1ActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Imagen seleccionada");

        txtUrlImagen1.setBorder(null);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel15))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUrlImagen1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExplorar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addComponent(jlImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExplorar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(2, 2, 2)
                .addComponent(txtUrlImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlImagen1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Codigo");

        txtNombre1.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre1.setCaretColor(new java.awt.Color(51, 51, 255));
        txtNombre1.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtNombre1.setDisabledTextColor(new java.awt.Color(51, 204, 0));
        txtNombre1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNombre1.setPhColor(new java.awt.Color(51, 51, 51));
        txtNombre1.setPlaceholder("Ingrese el nombre");
        txtNombre1.setSelectionColor(new java.awt.Color(51, 51, 51));

        txtPrecio1.setForeground(new java.awt.Color(51, 51, 51));
        txtPrecio1.setCaretColor(new java.awt.Color(51, 51, 255));
        txtPrecio1.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtPrecio1.setDisabledTextColor(new java.awt.Color(51, 204, 0));
        txtPrecio1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtPrecio1.setPhColor(new java.awt.Color(51, 51, 51));
        txtPrecio1.setPlaceholder("Ingrese el precio");
        txtPrecio1.setSelectionColor(new java.awt.Color(51, 51, 51));
        txtPrecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecio1ActionPerformed(evt);
            }
        });

        txtCodigo.setForeground(new java.awt.Color(51, 51, 51));
        txtCodigo.setCaretColor(new java.awt.Color(51, 51, 255));
        txtCodigo.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtCodigo.setDisabledTextColor(new java.awt.Color(51, 204, 0));
        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCodigo.setPhColor(new java.awt.Color(51, 51, 51));
        txtCodigo.setPlaceholder("");
        txtCodigo.setSelectionColor(new java.awt.Color(51, 51, 51));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        CbCategoria1.setBorder(null);
        CbCategoria1.setForeground(new java.awt.Color(51, 51, 51));
        CbCategoria1.setColorMaterial(new java.awt.Color(58, 179, 28));
        CbCategoria1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel16)
                                        .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPrecio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CbCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(BtnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnGuardarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(4, 4, 4)
                        .addComponent(CbCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        FormullarioModificar.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 110, -1, 450));

        PanelCubierta.addTab("tab2", FormullarioModificar);

        jPanel1.add(PanelCubierta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 800, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 16, 112, 33));

        BotonNuevo.setBackground(new java.awt.Color(58, 179, 28));
        BotonNuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonNuevo.setForeground(new java.awt.Color(255, 255, 255));
        BotonNuevo.setText("Nuevo");
        BotonNuevo.setBorder(null);
        BotonNuevo.setBorderPainted(false);
        BotonNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(BotonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 67, 112, 35));

        btnModificar.setBackground(new java.awt.Color(58, 179, 28));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.setBorder(null);
        btnModificar.setBorderPainted(false);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 67, 112, 35));

        jButton3.setBackground(new java.awt.Color(58, 179, 28));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 70, 50, 30));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 70, 140, 30));

        btnEliminar.setBackground(new java.awt.Color(58, 179, 28));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Borrar");
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 67, 112, 35));

        Seccion.setBackground(new java.awt.Color(255, 255, 255));
        Seccion.setForeground(new java.awt.Color(51, 51, 51));
        Seccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        PanelCarnes.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelCarnesLayout = new javax.swing.GroupLayout(PanelCarnes);
        PanelCarnes.setLayout(PanelCarnesLayout);
        PanelCarnesLayout.setHorizontalGroup(
            PanelCarnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        PanelCarnesLayout.setVerticalGroup(
            PanelCarnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(PanelCarnes);

        Seccion.addTab("Carnes", jScrollPane1);

        PanelDelChef.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelDelChefLayout = new javax.swing.GroupLayout(PanelDelChef);
        PanelDelChef.setLayout(PanelDelChefLayout);
        PanelDelChefLayout.setHorizontalGroup(
            PanelDelChefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        PanelDelChefLayout.setVerticalGroup(
            PanelDelChefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(PanelDelChef);

        Seccion.addTab("Del Chef", jScrollPane3);

        PanelEjecutivo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelEjecutivoLayout = new javax.swing.GroupLayout(PanelEjecutivo);
        PanelEjecutivo.setLayout(PanelEjecutivoLayout);
        PanelEjecutivoLayout.setHorizontalGroup(
            PanelEjecutivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        PanelEjecutivoLayout.setVerticalGroup(
            PanelEjecutivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(PanelEjecutivo);

        Seccion.addTab("Ejecutivo", jScrollPane4);

        PanelSopas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelSopasLayout = new javax.swing.GroupLayout(PanelSopas);
        PanelSopas.setLayout(PanelSopasLayout);
        PanelSopasLayout.setHorizontalGroup(
            PanelSopasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        PanelSopasLayout.setVerticalGroup(
            PanelSopasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jScrollPane5.setViewportView(PanelSopas);

        Seccion.addTab("Sopas", jScrollPane5);

        PanelPescado.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelPescadoLayout = new javax.swing.GroupLayout(PanelPescado);
        PanelPescado.setLayout(PanelPescadoLayout);
        PanelPescadoLayout.setHorizontalGroup(
            PanelPescadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        PanelPescadoLayout.setVerticalGroup(
            PanelPescadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jScrollPane6.setViewportView(PanelPescado);

        Seccion.addTab("Pescados", jScrollPane6);

        PanelBebida.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelBebidaLayout = new javax.swing.GroupLayout(PanelBebida);
        PanelBebida.setLayout(PanelBebidaLayout);
        PanelBebidaLayout.setHorizontalGroup(
            PanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
        );
        PanelBebidaLayout.setVerticalGroup(
            PanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jScrollPane7.setViewportView(PanelBebida);

        Seccion.addTab("Bebidas", jScrollPane7);

        PanelAdicional.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelAdicionalLayout = new javax.swing.GroupLayout(PanelAdicional);
        PanelAdicional.setLayout(PanelAdicionalLayout);
        PanelAdicionalLayout.setHorizontalGroup(
            PanelAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        PanelAdicionalLayout.setVerticalGroup(
            PanelAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jScrollPane8.setViewportView(PanelAdicional);

        Seccion.addTab("Adicionales", jScrollPane8);

        jPanel1.add(Seccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoActionPerformed
        FormularioNuevo.setBackground(new Color(230, 230, 230, 240));
        PanelCubierta.setVisible(true);
        PanelCubierta.removeAll();
        PanelCubierta.repaint();
        PanelCubierta.revalidate();
        PanelCubierta.add(FormularioNuevo);
        PanelCubierta.repaint();
        PanelCubierta.revalidate();
    }//GEN-LAST:event_BotonNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        objetoMenu.limpiarFormulario(txtNombre1, txtPrecio1, txtUrlImagen1, jlImagen1, archivoseleccionado, CbCategoria1);
        String codigo = objetoMenu.obtenerCodigoDelItem();

        if (codigo == null || codigo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un item antes de modificar.");
            return;
        }

        objetoMenu.obtenerDatosCompletos(codigo);
        imageIcon = (ImageIcon) jlImagen1.getIcon();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void BtnGuardarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarModificarActionPerformed
       objetoMenu.modificarMenu(txtCodigo, txtNombre1, txtPrecio1, archivoseleccionado, CbCategoria1);
       mostrarMenu();
       PanelCubierta.setVisible(false);
    }//GEN-LAST:event_BtnGuardarModificarActionPerformed

    private void BtnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalir1ActionPerformed
        PanelCubierta.setVisible(false);
    }//GEN-LAST:event_BtnSalir1ActionPerformed

    private void btnExplorar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExplorar1ActionPerformed
        JFileChooser filechooser = new JFileChooser();
        int result = filechooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            archivoseleccionado = filechooser.getSelectedFile();
            txtUrlImagen1.setText(archivoseleccionado.getName());

            try {
                Image img = ImageIO.read(archivoseleccionado);
                ImageIcon originalIcon = new ImageIcon(img);
                int ancho = jlImagen1.getWidth();
                int altura = jlImagen1.getHeight();
                Image ImagenEscalada = originalIcon.getImage().getScaledInstance(ancho, altura, Image.SCALE_SMOOTH);
                jlImagen1.setIcon(new ImageIcon(ImagenEscalada));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al mostrar imagen");
            }
        }
    }//GEN-LAST:event_btnExplorar1ActionPerformed

    private void btnExplorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExplorarActionPerformed
        JFileChooser filechooser = new JFileChooser();
        int result = filechooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            archivoseleccionado = filechooser.getSelectedFile();
            txtUrlImagen.setText(archivoseleccionado.getName());

            try {
                Image img = ImageIO.read(archivoseleccionado);
                ImageIcon originalIcon = new ImageIcon(img);
                int ancho = jlImagen.getWidth();
                int altura = jlImagen.getHeight();
                Image ImagenEscalada = originalIcon.getImage().getScaledInstance(ancho, altura, Image.SCALE_SMOOTH);
                jlImagen.setIcon(new ImageIcon(ImagenEscalada));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al mostrar imagen");
            }
        }
    }//GEN-LAST:event_btnExplorarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        PanelCubierta.setVisible(false);
        objetoMenu.limpiarFormulario(txtNombre, txtPrecio, txtUrlImagen, jlImagen, archivoseleccionado, CbCategoria);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        objetoMenu.agregarMenu(txtNombre, txtPrecio, archivoseleccionado, CbCategoria);
        mostrarMenu();
        PanelCubierta.setVisible(false);
        objetoMenu.limpiarFormulario(txtNombre, txtPrecio, txtUrlImagen, jlImagen, archivoseleccionado, CbCategoria);
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        objetoMenu.eliminarMenu();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtUrlImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUrlImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUrlImagenActionPerformed

    private void txtPrecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecio1ActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    public void mostrarDatoFormulario(String codigo, String nombre, float precio, int categoria, ImageIcon imagen) {
        txtCodigo.setText(codigo);
        txtNombre1.setText(nombre);
        txtPrecio1.setText(String.valueOf(precio));
        
        for (int i = 0; i < CbCategoria1.getItemCount(); i++) {
            if (CbCategoria1.getItemAt(i).toString().equals(String.valueOf(categoria))) {
                CbCategoria1.setSelectedIndex(i);
                break;
            }
        }

        jlImagen1.setIcon(imagen);
        FormullarioModificar.setBackground(new Color(230, 230, 230, 240));
        PanelCubierta.setVisible(true);
        PanelCubierta.removeAll();
        PanelCubierta.repaint();
        PanelCubierta.revalidate();
        PanelCubierta.add(FormullarioModificar);
        PanelCubierta.repaint();
        PanelCubierta.revalidate();

    }
    
    public void mostrarMenu(){
        Map<Integer, JPanel> panelesPorCategoria = new HashMap<>();
        panelesPorCategoria.put(1, PanelCarnes);
        panelesPorCategoria.put(2, PanelDelChef);
        panelesPorCategoria.put(3, PanelEjecutivo);
        panelesPorCategoria.put(4, PanelSopas);
        panelesPorCategoria.put(5, PanelPescado);
        panelesPorCategoria.put(6, PanelBebida);
        panelesPorCategoria.put(7, PanelAdicional);
        objetoMenu.mostrarMenu(panelesPorCategoria);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonNuevo;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnGuardarModificar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSalir1;
    private RSMaterialComponent.RSComboBoxMaterial CbCategoria;
    private RSMaterialComponent.RSComboBoxMaterial CbCategoria1;
    private javax.swing.JPanel FormularioNuevo;
    private javax.swing.JPanel FormullarioModificar;
    private javax.swing.JPanel PanelAdicional;
    private javax.swing.JPanel PanelBebida;
    private javax.swing.JPanel PanelCarnes;
    private javax.swing.JTabbedPane PanelCubierta;
    private javax.swing.JPanel PanelDelChef;
    private javax.swing.JPanel PanelEjecutivo;
    private javax.swing.JPanel PanelPescado;
    private javax.swing.JPanel PanelSopas;
    private javax.swing.JTabbedPane Seccion;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExplorar;
    private javax.swing.JButton btnExplorar1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlImagen;
    private javax.swing.JLabel jlImagen1;
    private RSMaterialComponent.RSTextFieldMaterial txtCodigo;
    private RSMaterialComponent.RSTextFieldMaterial txtNombre;
    private RSMaterialComponent.RSTextFieldMaterial txtNombre1;
    private RSMaterialComponent.RSTextFieldMaterial txtPrecio;
    private RSMaterialComponent.RSTextFieldMaterial txtPrecio1;
    private javax.swing.JTextField txtUrlImagen;
    private javax.swing.JTextField txtUrlImagen1;
    // End of variables declaration//GEN-END:variables
}
